# similar to https://github.com/openshift/machine-api-operator/blob/master/install/0000_30_machine-api-operator_00_credentials-request.yaml
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  # labels:
  #   controller-tools.k8s.io: "1.0"
  name: openshift-machine-api-aws-cloud-fencing
  namespace: openshift-cloud-credential-operator
  # annotations:
  #   exclude.release.openshift.io/internal-openshift-hosted: "true"
  #   include.release.openshift.io/self-managed-high-availability: "true"
spec:
  serviceAccountNames:
  - fence-agents-remediation-controller-manager
  secretRef:
    name: aws-cloud-fencing-credentials-secret
    namespace: openshift-operators
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
# https://github.com/openshift/cloud-credential-operator/blob/master/pkg/apis/cloudcredential/v1/types_aws.go
    statementEntries:
    - action:
      - ec2:StartInstances
      - ec2:StopInstances
      effect: Allow
      resource: "*"
